sudo: required

language: cpp

dist:
    - bionic
    - xenial
    - trusty

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
      - cmake
      - g++
      - python-dev
      - libgl1-mesa-glx
      - freeglut3-dev
      - libopenal-dev
      - libsdl-gfx1.2-dev
      - libvorbis-dev
      - libjpeg-dev
      - libpng-dev
      - libgtk2.0-dev
      - libboost-dev

script:
  - ./sh/vsbuild.sh
