sudo: required

language: cpp

compiler:
    - gcc
    - clang
    
jobs:
    include:
        - os: linux
          dist: trusty
        - os: linux
          dist: xenial
        - os: linux
          dist: bionic

addons:
  apt:
    packages:
      - cmake
      - g++
      - clang
      - python-dev
      - libgl1-mesa-glx
      - freeglut3-dev
      - libopenal-dev
      - libsdl-gfx1.2-dev
      - libvorbis-dev
      - libjpeg-dev
      - libpng-dev
      - libgtk2.0-dev
      - libboost-dev

script:
  - ./sh/vsbuild.sh
