language: cpp
os:
 - windows
 
before_install:
  - cd ../vcpkg
  # Check if cache was loaded. If yes, update it, otherwise clone a fresh copy
#  - test -d .git && { PREV="$(git rev-parse HEAD)" && git pull } || git clone https://github.com/Microsoft/vcpkg .
  - test -d .git && git pull || git clone https://github.com/Microsoft/vcpkg .
  # Update only if there's something new
#  - test "$PREV" == "$(git rev-parse HEAD)" || ./bootstrap-vcpkg.bat
  - ./bootstrap-vcpkg.bat
  - export VCPKG="$PWD"
  - cd -

install:
  - $VCPKG/vcpkg install python2:x64-windows
    #- $travis_wait 60 VCPKG/vcpkg install python3:x64-windows
  - $VCPKG/vcpkg install gtk:x64-windows
  - $VCPKG/vcpkg install libpng:x64-windows
  - $VCPKG/vcpkg install libjpeg-turbo:x64-windows
  - $VCPKG/vcpkg install freeglut:x64-windows
  - $VCPKG/vcpkg install sdl1:x64-windows
  - $VCPKG/vcpkg install openal-soft:x64-windows
  - $VCPKG/vcpkg install libvorbis:x64-windows
    #- travis_wait 60 $VCPKG/vcpkg install boost:x64-windows

before_script:
    - mkdir -p ext
    - curl https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.zip > boost.zip
    - Expand-Archive boost.zip -DestinationPath ext/boost

script:
  - VMAKE="$VCPKG/scripts/buildsystems/vcpkg.cmake"
  - mkdir build && cd build
  - echo $VMAKE
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$VMAKE" -G "Visual Studio 15 2017 Win64" ../engine
  - cmake --build .
  - mkdir ../bin
  - cp vegastrike ../bin
  - cp setup/vssetup ../bin
  - cp objconv/mesh_tool ../bin

cache:
  directories:
    - ../vcpkg
    - ext
