language: cpp
os:
 - windows
 
before_install:
  - cd ../vcpkg
  # Check if cache was loaded. If yes, update it, otherwise clone a fresh copy
  - if test -d .git; then PREV="$(git rev-parse HEAD)"; git pull; else git clone https://github.com/Microsoft/vcpkg .; fi
  # Update only if there's something new
  - if test "$PREV" != "$(git rev-parse HEAD)"; then ./bootstrap-vcpkg.bat; fi
  - export VCPKG="$PWD"
  - cd -

install:
  - $VCPKG/vcpkg install python2:x86-windows
    #- $travis_wait 60 VCPKG/vcpkg install python3:x86-windows
  - $VCPKG/vcpkg install gtk:x86-windows
  - $VCPKG/vcpkg install libpng:x86-windows
  - $VCPKG/vcpkg install libjpeg-turbo:x86-windows
  - $VCPKG/vcpkg install freeglut:x86-windows
  - $VCPKG/vcpkg install sdl1:x86-windows
  - $VCPKG/vcpkg install openal-soft:x86-windows
  - $VCPKG/vcpkg install libvorbis:x86-windows
    #- travis_wait 60 $VCPKG/vcpkg install boost:x86-windows

before_script:
    # No need to explicitly make the directory, since Travis-CI caching functionality will do it automatically
    #- mkdir -p ext
    - test ! -d ext/boost_1_72_0 && wget -nv https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.zip -O boost.zip || return 0
    - test ! -d ext/boost_1_72_0 && unzip -q boost.zip -d ext/ && rm boost.zip || return 0

script:
  - VMAKE="$VCPKG/scripts/buildsystems/vcpkg.cmake"
  - mkdir build && cd build
  - echo $VMAKE
  - cmake -DCMAKE_BUILD_TYPE=Debug -A Win32 -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF -DCMAKE_TOOLCHAIN_FILE="$VMAKE" -DUSE_SYSTEM_BOOST=OFF -G "Visual Studio 16 2019" ../engine
  - cmake --build . #> output.log 2>error.log

after_success:
  - mkdir ../bin
  - cp vegastrike.exe ../bin
  - cp setup/vssetup.exe ../bin
  - cp objconv/mesh_tool.exe ../bin

after_failure:
    #- zip output.zip output.log
    #- curl --upload-file 'output.log' 'https://paste.c-net.org/'
    #- tail -n20 output.log
    #- tail -n20 error.log
    #- grep -wi error output.log -A2
    #- grep -wi error error.log -A2

cache:
  directories:
    - ../vcpkg
    - ext
