language: cpp

jobs:
    include:
        - os: windows
          env: VCPKG_DEFAULT_TRIPLET=x86-windows EXT=bat BIN_EXT=exe
        - os: osx
          osx_image: xcode11.4
          env: VCPKG_DEFAULT_TRIPLET=x64-osx EXT=sh
        - os: linux
          dist: bionic
          env: VCPKG_DEFAULT_TRIPLET=x64-linux EXT=sh

before_install:
  - cd ../vcpkg
  # Check if cache was loaded. If yes, update it, otherwise clone a fresh copy
  - if test -d .git; then PREV="$(git rev-parse HEAD)"; git pull; else git clone https://github.com/Microsoft/vcpkg .; fi
  # Update only if there's something new
  - if test "$PREV" != "$(git rev-parse HEAD)"; then ./bootstrap-vcpkg.$EXT; fi
  - export VCPKG="$PWD"
  - cd -

install:
  #- $VCPKG/vcpkg install python2
    #- $travis_wait 60 VCPKG/vcpkg install python3
  - $VCPKG/vcpkg install gtk
  - $VCPKG/vcpkg install libpng
  - $VCPKG/vcpkg install libjpeg-turbo
  - $VCPKG/vcpkg install freeglut
  - $VCPKG/vcpkg install sdl1
  - $VCPKG/vcpkg install openal-soft
  - $VCPKG/vcpkg install libvorbis
    #- travis_wait 60 $VCPKG/vcpkg install boost

before_script:
    # No need to explicitly make the directory, since Travis-CI caching functionality will do it automatically
    #- mkdir -p ext
    - test ! -d ext/boost_1_72_0 && wget -nv https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.zip -O boost.zip || return 0
    - test ! -d ext/boost_1_72_0 && unzip -q boost.zip -d ext/ && rm boost.zip || return 0

script:
  - VMAKE="$VCPKG/scripts/buildsystems/vcpkg.cmake"
  - mkdir build && cd build
  - echo $VMAKE
  - cmake -DCMAKE_BUILD_TYPE=Debug -A Win32 -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF -DCMAKE_TOOLCHAIN_FILE="$VMAKE" -DUSE_SYSTEM_BOOST=OFF -DUSE_PYTHON_3=ON -G "Visual Studio 15 2017" ../engine
  - cmake --build . #> output.log 2>error.log

after_success:
  - mkdir ../bin
  - cp vegastrike.$BIN_EXT ../bin
  - cp setup/vssetup.$BIN_EXT ../bin
  - cp objconv/mesh_tool.$BIN_EXT ../bin

after_failure:
    #- zip output.zip output.log
    #- curl --upload-file 'output.log' 'https://paste.c-net.org/'
    #- tail -n20 output.log
    #- tail -n20 error.log
    #- grep -wi error output.log -A2
    #- grep -wi error error.log -A2

cache:
  directories:
    - ../vcpkg
    - ext
