version: 2.0.0.{build}

os:
  - Windows Server 2012 R2

environment:
  matrix:
  - CMAKE_GENERATOR: Visual Studio 14 2015
  - CMAKE_GENERATOR: Visual Studio 15 2017

before_build:
  # Generate solution files using cmake, in 'builds' directory.
  # No need to create it because it's part of the repo.
  - pushd .. && git clone https://github.com/Microsoft/vcpkg && pushd vcpkg && .\bootstrap-vcpkg.bat && popd && popd
  - ..\vcpkg\vcpkg install gtk:x64-windows sdl1:x64-windows python2:x64-windows libpng:x64-windows libjpeg-turbo:x64-windows freeglut:x64-windows openal-soft:x64-windows libvorbis:x64-windows
  - mkdir build && pushd build && cmake -G "%CMAKE_GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ../engine && popd

configuration:
  - Debug
  - Release

build_script:
  - pushd build && cmake --build . && popd

matrix:
  fast_finish: true
  
cache:
  - ..\vcpkg -> appveyor.yml
